name: crud
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  chewie: ^0.9.10
  # firestore
  cloud_firestore:
  firebase_auth: ^0.18.0
  firebase_core: ^0.5.0
  firebase_storage: ^4.0.0
  firebase_messaging: ^7.0.0

  flutter_dotenv: ^2.1.0
  fluttertoast: ^7.0.2
  http: ^0.12.1
  intl: ^0.16.1
  video_player: ^0.10.11+2
  url_launcher: ^ 5.5.0
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.3
  algolia: ^0.1.7
  cloud_functions: ^0.6.0
  table_calendar: ^2.2.3
  flutter_launcher_icons: ^0.7.5
  flutter_linkify: ^3.1.3
  jiffy: ^3.0.1

  shared_preferences: ^0.5.12+2
  flutter_slidable: ^0.5.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
